#You must provide the following variables for your dev CassieQ container when recording new cassettes for tests
#host: the host for the dev CassieQ container
#key: must be an cassieq auth key generated for account
#provided_params: must be cassieq signed query string auth generated for account with level ["g"] permission

host: 192.168.99.100
account: test-account
key: C3RAOAbRVT-MBe7DL491-3oAzNJrzhqcYRANlNPqvSPcCUtTYa7flyhDpSPEM01b4bzNaQL1uvLMm5y4HDY3bA
provided_params: auth=g&sig=JkGhEjsPBwrRbo2UGEwQd1vAaMfD_IrlKk3LkPxoDgA
