#You must provide the following variables for your dev CassieQ container when recording new cassettes for tests
#host: the host for the dev CassieQ container
#key: must be an cassieq auth key generated for account
#provided_params: must be cassieq signed query string auth generated for account with level ["g"] permission

host: 192.168.99.100
account: test-account
key: A1wOkHNznfi131jjuHmd61OQKPq5Su0hJVUf8WvmKHGHQMT5scgTeiDJWEBE-jt5nNzHMKBAu0pRC9aChxpLrQ
provided_params: auth=g&sig=MkvORZbS11AS-pM1vFjfPPSdKEMSON6bPN6pF7n4zv0
